---
SATELLITE_DISTRIBUTION: "{{ lookup('env','SATELLITE_DISTRIBUTION') }}"
DOWNLOAD_POLICY: "{{ lookup('env','DOWNLOAD_POLICY') }}"
SAT_VERSION: "{{ lookup('env','SAT_VERSION') }}"
RHEL6_TOOLS_PRD: "Red Hat Enterprise Linux Server"
RHEL6_TOOLS_REPO: "Red Hat Satellite Tools {{ SAT_VERSION }} for RHEL 6 Server RPMs x86_64"
RHEL7_TOOLS_PRD: "Red Hat Enterprise Linux Server"
RHEL7_TOOLS_REPO: "Red Hat Satellite Tools {{ SAT_VERSION }} for RHEL 7 Server RPMs x86_64"
SAT6C6_PRODUCT: "Red Hat Satellite Capsule Beta"
CAPSULE6_REPO: "Red Hat Satellite Capsule {{ SAT_VERSION }} for RHEL 6 Server RPMs x86_64"
SAT6C7_PRODUCT: "Red Hat Satellite Capsule Beta"
CAPSULE7_REPO: "Red Hat Satellite Capsule {{ SAT_VERSION }} for RHEL 7 Server RPMs x86_64"
SAT6M7_PRODUCT: "Red Hat Enterprise Linux Server"
MAINTAIN7_REPO: "Red Hat Satellite Maintenance 6 for RHEL 7 Server RPMs x86_64"
