---
- name: create_activation_keys
  hosts: satellite
  vars:
    username: admin
    password: changeme # to do part
    SERVER_HOSTNAME: "{{ lookup('env','SERVER_HOSTNAME') }}"
    server_url: "https://{{ SERVER_HOSTNAME }}"
    SATELLITE_DISTRIBUTION: "{{ lookup('env','SATELLITE_DISTRIBUTION') }}"
    DOWNLOAD_POLICY: "{{ lookup('env','DOWNLOAD_POLICY') }}"
    SAT_VERSION: "{{ lookup('env','SAT_VERSION') }}"
    organization: "Test Organization"
  tasks:
    - name: Load vars when SATELLITE_DISTRIBUTION == BETA
      include_vars: sat_beta_vars.yml
      when: SATELLITE_DISTRIBUTION == "BETA"
    - name: Load vars when SATELLITE_DISTRIBUTION == GA
      include_vars: sat_ga_vars.yml
      when: SATELLITE_DISTRIBUTION == "GA"
    - name: Load vars when SATELLITE_DISTRIBUTION != ("GA" and "BETA")
      include_vars: sat_internalak_vars.yml
      when:
        - SATELLITE_DISTRIBUTION != "GA"
        - SATELLITE_DISTRIBUTION != "BETA"
    - name: Create lifecycle-environments
      include_tasks: tasks/create_lifecycle_environment.yml
      loop:
        - lifecycle_environment_name: "DEV"
          organization: "{{ organization }}"
          prior: "Library"
        - lifecycle_environment_name: "QE"
          organization: "{{ organization }}"
          prior: "DEV"
        - lifecycle_environment_name: "PROD"
          organization: "{{ organization }}"
          prior: "QE"