---
- hosts: localhost
  vars:
  environment:
    DISTRO: rhel7
  tasks:
    - name: 'source configuration files'
      shell: 'source ${CONFIG_FILES}'
      shell: 'source config/sat6_repos_urls.conf && source config/subscription_config.conf'
    - name: ' pip install -U -r requirements.txt'
      pip:
        requirements: requirements.txt
        extra_args: -U,-r
    - name: 'copy testfm.properties.sample and testfm/inventory.sample'
      copy:
        src: {{ item.0 }}
        dest: {{ item.1}}
      with_together:
        - [ 'testfm.properties.sample', 'testfm/inventory.sample']
        - [ 'testfm.properties', 'testfm/inventory']
