- name: "Create Product"
  katello_product:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "{{ item.product }}"
    organization: "{{ item.organization }}"
    state: present

- name: "Enable Red Hat repositories"
  katello_repository_set:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    name: "{{ item.repo_name }}"
    organization: "{{ item.organization }}"
    product: "{{ item.product }}"
    repositories:
    - releasever: "{{ item.releasever | default(omit) }}"
      basearch: "{{ item.basearch | default(omit) }}"
    state: enabled
