- name: "Create Product"
  katello_product:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server }}"
    name: "{{ product }}"
    organization: "{{ organization }}"
    state: present

- name: "Enable Red Hat repositories"
  katello_repository_set:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server }}"
    name: "{{ repo_name }}"
    organization: "{{ organization }}"
    product: "{{ product }}"
    repositories:
    - releasever: "{{ releasever }}"
      basearch: "{{ basearch }}"
    state: enabled

- name: "Sync repository"
  katello_sync:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server }}"
    repository: "{{ repo_name }}"
    product: "{{ product }}"
    organization: "{{ organization }}"