- name: "Create Product"
  katello_product:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server }}"
    name: "{{ item.product }}"
    organization: "{{ item.organization }}"
    state: present

- name: "Enable Red Hat repositories"
  katello_repository_set:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server }}"
    name: "{{ item.repo_name }}"
    organization: "{{ item.organization }}"
    product: "{{ item.product }}"
    repositories:
    - releasever: "{{ item.releasever }}"
      basearch: "{{ item.basearch }}"
    state: enabled

- name: "Sync repository"
  katello_sync:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server }}"
    repository: "{{ item.repo_name }}"
    product: "{{ item.product }}"
    organization: "{{ item.organization }}"